# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # 기본 파일 체크
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
        exclude: ^playbooks/.*\.yml$  # Ansible 플레이북은 ansible-lint로 검사
      - id: check-json
        name: Check JSON syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=5000']
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: detect-private-key
        name: Detect private keys
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']

  # Python 코드 포매팅
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        name: Ruff linter
        args: ['--fix']
      - id: ruff-format
        name: Ruff formatter

  # Ansible 린팅
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.22.1
    hooks:
      - id: ansible-lint
        name: Ansible lint
        files: \.(yaml|yml)$
        exclude: ^(inventory/|group_vars/|\.github/)

  # Shell 스크립트 검사
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: ShellCheck
        exclude: ^docker-entrypoint\.sh$

  # YAML 포매팅
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Prettier formatter
        types_or: [yaml, json]
        exclude: ^(playbooks/|inventory/|group_vars/|ansible\.cfg)

  # Dockerfile 린팅
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Dockerfile linter
        entry: hadolint/hadolint:latest-alpine hadolint
        language: docker_image

  # 보안 검사
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        name: Detect secrets

  # Markdown 린팅
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        name: Markdown lint
        args: ['--fix']

# 전역 설정
default_language_version:
  python: python3.11

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false