---
- hosts: mons[0]
  become: true
  vars_files:
    - ../../ceph-vars.yml
  tasks:
    - name: Include RGW bucket creation tasks
      include_tasks: ../02-services/tasks/rgw_bucket_creation.yml
      loop: "{{ ceph.rgw }}"
      loop_control:
        loop_var: rgw_instance
      when: ceph.rgw is defined and ceph.rgw | length > 0